on: [push]
jobs:
  build-all-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm clean-install
      - run: npm run build --workspaces
      - run: npm run test -w packages/z80-asm
      - run: npm run test -w packages/z80-disasm
      - run: npm run test -w packages/z80-emulator
      - uses: actions/upload-artifact@v4
        with:
          name: my-trs-80
          path: packages/my-trs-80/build/
      - uses: actions/upload-artifact@v4
        with:
          name: trs80-cassette-webapp
          path: packages/trs80-cassette-webapp/build/
      - uses: actions/upload-artifact@v4
        with:
          name: trs80-ide
          path: packages/trs80-ide/dist/
      - run: npm run buildBinaries -w packages/trs80-tool
      - uses: actions/upload-artifact@v4
        with:
          name: trs80-tool-linux
          path: packages/trs80-tool/binaries/trs80-tool/linux/trs80-tool
      - uses: actions/upload-artifact@v4
        with:
          name: trs80-tool-macos
          path: packages/trs80-tool/binaries/trs80-tool/macos/trs80-tool
      - uses: actions/upload-artifact@v4
        with:
          name: trs80-tool-windows
          path: packages/trs80-tool/binaries/trs80-tool/windows/trs80-tool.exe
      - uses: actions/upload-artifact@v4
        with:
          name: trs80-tool-site
          path: packages/trs80-tool/site/
